#!/bin/sh

cd /c/Users/Slacky/eclipse-workspace-telink/ts0207_tz3000_zed

rm ./bin/*.zigbee
rm ./bin/zg_222*.bin
rm ./bin/snzb*.bin

make clean
make CHECK_BL=1 BOARD_NAME=ZG_222ZA

make clean
make BOARD_NAME=ZG_222ZA

make clean
make BOARD_NAME=ZG_222Z

make clean
make BOARD_NAME=SNZB_05